# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(710, 401)
        main_window.setMinimumSize(QtCore.QSize(710, 401))
        main_window.setMaximumSize(QtCore.QSize(710, 401))
        self.label = QtWidgets.QLabel(main_window)
        self.label.setGeometry(QtCore.QRect(0, 0, 711, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/login/images/images.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(main_window)
        self.layoutWidget.setGeometry(QtCore.QRect(169, 29, 331, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 24pt \"Cairo\";")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.predict_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.predict_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.predict_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/predict_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.predict_btn.setIcon(icon)
        self.predict_btn.setIconSize(QtCore.QSize(24, 24))
        self.predict_btn.setObjectName("predict_btn")
        self.verticalLayout.addWidget(self.predict_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.loginout_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.loginout_btn.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginout_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/logout_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginout_btn.setIcon(icon1)
        self.loginout_btn.setIconSize(QtCore.QSize(24, 24))
        self.loginout_btn.setObjectName("loginout_btn")
        self.verticalLayout.addWidget(self.loginout_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "main_window"))
        self.label_24.setText(_translate("main_window", "Chest Exploration"))
        self.predict_btn.setText(_translate("main_window", "check x-ray"))
        self.loginout_btn.setText(_translate("main_window", "   Log out"))
import app_resources_rc
